travis:
  secure:
    BINSTAR_TOKEN: ZKouW8Zti7FIWkZ0xEHBYJRAt3JNzbylwaqqHNdY1R5UqVzxyMrws7IejA7pqLRf0HCfMkuQ6Wx/pJJa2DO5yH/0ct2GeEWd2f0RtQm3cCbLZ4H4CqCp2MYaLoj/3UdBi86SCAKd8UPn1SKxVVk84hnLZRta9+izVtcl3RYp3Pc9ww5Pwmr5MNfrdx0QKvc9q8u4p4UkzouMRwSMStYmGWzJLozwpyueL42cmBEQcA55WiIBIVOXtWEIf5U9inhomNKuFy7f4jJp08aYHJ6svin07G7DAMrByxubmRV2QcxTXRazbYxBB8VJO4ckueGhtPsqHa5jkZEH0EDZirox5HT17nmEg9kdytjG0gRG53TdFzy/HkkAeQPeDJdnd030/+IQTyUXJ/6u713LYbsWnQOsBgjKRFm3CHlx6WrTXUE+GOTJuXEVfIMB2jQt4Y2s7Y30yXMeEv9og5Cxn7AeMzN++f8/SJkI7NvLRYj4Z2+nUG6houcQvXMTbKrHSGIlydbhtw2Bxnr94+HvOGM1oHnv0JBUBTazpe8vA/fBUQinTUtXlI8We2wadvglEjdd0azGmIt1YwiNOw5qiQMCYaWnWPpQFs9GtYSXT8B1CF0S6O+t/ip457Z9q+1ko6otfJTIaFZdgxIu1YI8E/uo0qTQq+jU6JADNKtp1XR4OjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
